# Generated by Django 4.1.2 on 2022-11-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0004_alter_profile_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_option', models.CharField(choices=[('Emergency Care', 'Emergency Care'), ('Operation & Surgery', 'Operation & Surgery'), ('Outdoor Checkup', 'Outdoor Checkup'), ('Ambulance service', 'Ambulance service'), ('Medicine & Pharmacy', 'Medicine & Pharmacy'), ('Blood tetsing', 'Blood Testing')], max_length=20, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('service_logo', models.ImageField(blank=True, null=True, upload_to='service_logo/')),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('HoD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_option', models.CharField(choices=[('Emergency Care', 'Emergency Care'), ('Operation & Surgery', 'Operation & Surgery'), ('Outdoor Checkup', 'Outdoor Checkup'), ('Ambulance service', 'Ambulance service'), ('Medicine & Pharmacy', 'Medicine & Pharmacy'), ('Blood tetsing', 'Blood Testing')], max_length=20, unique=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=50)),
                ('consultant_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('resident_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('payment', models.BooleanField(blank=True, default=False, null=True)),
                ('served', models.BooleanField(blank=True, default=False, null=True)),
                ('patient_status', models.CharField(choices=[('Booked for test', 'Booked for test'), ('Transferred', 'Transferred'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Dead', 'Dead')], max_length=20, null=True)),
                ('doctor_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
