# Generated by Django 4.1.2 on 2022-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_alter_bookingservice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
