# Generated by Django 4.1.2 on 2022-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0004_alter_bookingservice_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
