# Generated by Django 4.1.2 on 2022-11-29 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0005_bookingservice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingservice',
            name='hod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
