# Generated by Django 4.1.2 on 2022-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0006_bookingservice_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='service_option',
            field=models.CharField(choices=[('Emergency Care', 'Emergency Care'), ('Operation & Surgery', 'Operation & Surgery'), ('Outdoor Checkup', 'Outdoor Checkup'), ('Ambulance service', 'Ambulance service'), ('Medicine & Pharmacy', 'Medicine & Pharmacy'), ('Blood tetsing', 'Blood Testing')], max_length=20),
        ),
    ]
