# Generated by Django 4.1.2 on 2022-11-30 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0007_alter_bookingservice_service_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='consultant_doctor',
            field=models.ForeignKey(blank=True, default=1, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='patient_status',
            field=models.CharField(choices=[('----------', '----------'), ('Booked for test', 'Booked for test'), ('Transferred', 'Transferred'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Dead', 'Dead')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='resident_doctor',
            field=models.ForeignKey(blank=True, default=1, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
