# Generated by Django 4.1.2 on 2022-11-30 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0008_alter_bookingservice_consultant_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingservice',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
