# Generated by Django 4.1.2 on 2022-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
    ]
