# Generated by Django 4.1.2 on 2022-11-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='means_of_identifition',
        ),
        migrations.AddField(
            model_name='profile',
            name='means_of_identity',
            field=models.ImageField(null=True, upload_to='identityImage/'),
        ),
    ]
