# Generated by Django 4.1.2 on 2022-11-28 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services_app', '0004_alter_bookingservice_date_created'),
        ('user_app', '0004_alter_profile_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_service',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services_app.bookingservice')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile')),
            ],
        ),
    ]
